App_Pagina_Lenceria/urls.py
from django.urls import path

from . import views


app_name = 'App_Pagina_Lenceria'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
]

Pagina_Lenceria/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('App_Pagina_Lenceria/', include('App_Pagina_Lenceria.urls')),
    path('admin/', admin.site.urls),
]

App_Pagina_Lenceria/models.py
#from tkinter import CASCADE
# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Productor(models.Model):
    identificador = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    localidad = models.CharField(max_length=100)
    telefono = models.IntegerField()
    email = models.EmailField(max_length=100)

class Producto(models.Model):
    identificador = models.IntegerField(primary_key=True)
    precio_compra = models.FloatField(default=0)
    precio_venta = models.FloatField(default=0)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    talle = models.CharField(max_length=20)
    color = models.CharField(max_length=30)
    productor = models.ForeignKey(Productor, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    dni = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    telefono = models.IntegerField()
    def __str__(self):
        return self.nombre

class Factura(models.Model):
    identificador = models.IntegerField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    #[TODO] agregar la lista de productos comprados.
    fecha = models.DateField(auto_now=True)
    hora = models.TimeField(auto_now=True)
    def __str__(self):
        return self.cliente

App_Pagina_Lenceria/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'App_Pagina_Lenceria/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'App_Pagina_Lenceria/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'App_Pagina_Lenceria/results.html'


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'App_Pagina_Lenceria/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'App_Pagina_Lenceria/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'App_Pagina_Lenceria/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'App_Pagina_Lenceria/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('App_Pagina_Lenceria:results', args=(question.id,)))

Pagina_Lenceria/views.py
# Create your views here.
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.template.response import TemplateResponse



def home(request):
    #t = TemplateResponse(request, 'base.html', {})
    #t.render()
    #print("LOG--------------------- CONTENIDO: "+t.content)

    return HttpResponse("\
            <!-- Required meta tags -->\
            <meta charset=\"utf-8\">\
            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\
            <meta name=\"description\" content=\"\">\
            <meta name=\"author\" content=\"Matias Ducid\">\
            <meta name=\"generator\" content=\"Pagina_Lenceria v1.0\">\
            <title>Lencería Mabel</title>\
            <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.3/examples/product/\">\
            <!-- Bootstrap core CSS -->\
            <link href=\"/docs/4.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\
            <style>\
                .bd-placeholder-img {\
                font-size: 1.125rem;\
                text-anchor: middle;\
                -webkit-user-select: none;\
                -moz-user-select: none;\
                -ms-user-select: none;\
                user-select: none;\
                }\
                @media (min-width: 768px) {\
                .bd-placeholder-img-lg {\
                font-size: 3.5rem;\
                }\
            }\
            </style>\
            <!-- Custom styles for this template -->\
            <link href=\"static/css/producto.css\" rel=\"stylesheet\">\
            <!-- Bootstrap CSS -->\
            <!--<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">-->\
            <head>\
                <h1>Lencería Mabel.</h1> \
            </head>\
            <body>\
                <nav class=\"site-header sticky-top py-1\">\
                    <div class=\"container d-flex flex-column flex-md-row justify-content-between\">\
                        <a class=\"py-2\" href=\"#\">\
                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" class=\"d-block mx-auto\" role=\"img\" viewBox=\"0 0 24 24\" focusable=\"false\"><title>Product</title><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><path d=\"M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94\"></path></svg>\
                        </a>\
                        <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Mallas de mujer</a>\
                        <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Mallas de hombre</a>\
                        <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Medias</a>\
                        <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Lencería</a>\
                        <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Ropa interior masculina</a>\
                    </div>\
                </nav>\
                <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\
                <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\
                <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\
            </body>\
            ")









  

App_Pagina_Lenceria/templates/App_Pagina_Lenceria/detail.html
<form action="{% url 'App_Pagina_Lenceria:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
    

App_Pagina_Lenceria/templates/App_Pagina_Lenceria/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'App_Pagina_Lenceria:detail' question.id %}">
                {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

App_Pagina_Lenceria/templates/App_Pagina_Lenceria/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'App_Pagina_Lenceria:detail' question.id %}">Vote again?</a>

Pagina_Lenceria/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>